basePath: /api/v1
definitions:
  github_com_puremike_online_auction_api_internal_models.CreateUserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      full_name:
        maxLength: 32
        minLength: 6
        type: string
      location:
        maxLength: 42
        minLength: 6
        type: string
      password:
        type: string
      username:
        maxLength: 32
        minLength: 6
        type: string
    required:
    - confirm_password
    - email
    - full_name
    - location
    - password
    - username
    type: object
  github_com_puremike_online_auction_api_internal_models.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      location:
        type: string
      username:
        type: string
    type: object
  internal_handlers.healthResponse:
    properties:
      api_version:
        type: string
      environment:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: digitalmarketfy@gmail.com
    name: Puremike
    url: http://github.com/puremike
  description: This is an API for a Online Webbased Auction System
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Online Webbased Auction System API
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the status of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handlers.healthResponse'
      summary: Get health
      tags:
      - health
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_puremike_online_auction_api_internal_models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_puremike_online_auction_api_internal_models.UserResponse'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: 'Use a valid JWT token. Format: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
