services:
  db:
    image: postgres
    container_name: postgres-owas
    environment:
      POSTGRES_DB: OWAS
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword123
    volumes:
      - owas-pg-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  owas-pg-data:
