name: Server-CI

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
    
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with: 
                go-version: 1.24.3
            
            - name: Verify Dependencies
              working-directory: ./server
              run: go mod verify

            - name: Build
              working-directory: ./server
              run: go build -v ./...

            - name: Run go vet
              working-directory: ./server
              run: go vet ./...

            - name: Run tests\
              working-directory: ./server
              run: go test -race ./...

    